name: release.yml
on:
  workflow_dispatch:
  schedule:
    - cron: "25 12 * * *"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: dart-lang/dart-docker
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - run: docker login -u taras0mazepa -p ${{ secrets.DOCKER_PAT }}
      - run: docker buildx build --platform linux/amd64,linux/arm64v8,linux/arm32v7 -t taras0mazepa/dart:$(jq -r '.stable.version' ../../versions.json) --push .
        working-directory: stable/bookworm
